/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface ReputationBridgeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "jobManager"
      | "owner"
      | "recordJobOutcome"
      | "renounceOwnership"
      | "reputationRegistry"
      | "setJobManager"
      | "setReputationRegistry"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "JobManagerUpdated"
      | "OutcomeRecorded"
      | "OwnershipTransferred"
      | "ReputationRegistryUpdated"
      | "ReputationUpdateFailed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "jobManager",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordJobOutcome",
    values: [BigNumberish, AddressLike, AddressLike, boolean, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reputationRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setJobManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setReputationRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "jobManager", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordJobOutcome",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reputationRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setJobManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReputationRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace JobManagerUpdatedEvent {
  export type InputTuple = [oldManager: AddressLike, newManager: AddressLike];
  export type OutputTuple = [oldManager: string, newManager: string];
  export interface OutputObject {
    oldManager: string;
    newManager: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OutcomeRecordedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    agent: AddressLike,
    positive: boolean
  ];
  export type OutputTuple = [jobId: bigint, agent: string, positive: boolean];
  export interface OutputObject {
    jobId: bigint;
    agent: string;
    positive: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReputationRegistryUpdatedEvent {
  export type InputTuple = [oldRegistry: AddressLike, newRegistry: AddressLike];
  export type OutputTuple = [oldRegistry: string, newRegistry: string];
  export interface OutputObject {
    oldRegistry: string;
    newRegistry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReputationUpdateFailedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    agent: AddressLike,
    reason: BytesLike
  ];
  export type OutputTuple = [jobId: bigint, agent: string, reason: string];
  export interface OutputObject {
    jobId: bigint;
    agent: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReputationBridge extends BaseContract {
  connect(runner?: ContractRunner | null): ReputationBridge;
  waitForDeployment(): Promise<this>;

  interface: ReputationBridgeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  jobManager: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  recordJobOutcome: TypedContractMethod<
    [
      jobId: BigNumberish,
      provider: AddressLike,
      evaluator: AddressLike,
      completed: boolean,
      reason: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reputationRegistry: TypedContractMethod<[], [string], "view">;

  setJobManager: TypedContractMethod<
    [_jobManager: AddressLike],
    [void],
    "nonpayable"
  >;

  setReputationRegistry: TypedContractMethod<
    [_reputationRegistry: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "jobManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordJobOutcome"
  ): TypedContractMethod<
    [
      jobId: BigNumberish,
      provider: AddressLike,
      evaluator: AddressLike,
      completed: boolean,
      reason: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reputationRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setJobManager"
  ): TypedContractMethod<[_jobManager: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setReputationRegistry"
  ): TypedContractMethod<
    [_reputationRegistry: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "JobManagerUpdated"
  ): TypedContractEvent<
    JobManagerUpdatedEvent.InputTuple,
    JobManagerUpdatedEvent.OutputTuple,
    JobManagerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OutcomeRecorded"
  ): TypedContractEvent<
    OutcomeRecordedEvent.InputTuple,
    OutcomeRecordedEvent.OutputTuple,
    OutcomeRecordedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ReputationRegistryUpdated"
  ): TypedContractEvent<
    ReputationRegistryUpdatedEvent.InputTuple,
    ReputationRegistryUpdatedEvent.OutputTuple,
    ReputationRegistryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ReputationUpdateFailed"
  ): TypedContractEvent<
    ReputationUpdateFailedEvent.InputTuple,
    ReputationUpdateFailedEvent.OutputTuple,
    ReputationUpdateFailedEvent.OutputObject
  >;

  filters: {
    "JobManagerUpdated(address,address)": TypedContractEvent<
      JobManagerUpdatedEvent.InputTuple,
      JobManagerUpdatedEvent.OutputTuple,
      JobManagerUpdatedEvent.OutputObject
    >;
    JobManagerUpdated: TypedContractEvent<
      JobManagerUpdatedEvent.InputTuple,
      JobManagerUpdatedEvent.OutputTuple,
      JobManagerUpdatedEvent.OutputObject
    >;

    "OutcomeRecorded(uint256,address,bool)": TypedContractEvent<
      OutcomeRecordedEvent.InputTuple,
      OutcomeRecordedEvent.OutputTuple,
      OutcomeRecordedEvent.OutputObject
    >;
    OutcomeRecorded: TypedContractEvent<
      OutcomeRecordedEvent.InputTuple,
      OutcomeRecordedEvent.OutputTuple,
      OutcomeRecordedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ReputationRegistryUpdated(address,address)": TypedContractEvent<
      ReputationRegistryUpdatedEvent.InputTuple,
      ReputationRegistryUpdatedEvent.OutputTuple,
      ReputationRegistryUpdatedEvent.OutputObject
    >;
    ReputationRegistryUpdated: TypedContractEvent<
      ReputationRegistryUpdatedEvent.InputTuple,
      ReputationRegistryUpdatedEvent.OutputTuple,
      ReputationRegistryUpdatedEvent.OutputObject
    >;

    "ReputationUpdateFailed(uint256,address,bytes)": TypedContractEvent<
      ReputationUpdateFailedEvent.InputTuple,
      ReputationUpdateFailedEvent.OutputTuple,
      ReputationUpdateFailedEvent.OutputObject
    >;
    ReputationUpdateFailed: TypedContractEvent<
      ReputationUpdateFailedEvent.InputTuple,
      ReputationUpdateFailedEvent.OutputTuple,
      ReputationUpdateFailedEvent.OutputObject
    >;
  };
}
