/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockERC8004Registry } from "./MockERC8004Registry";
export type { MockUSDC } from "./MockUSDC";
