/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace MockERC8004Registry {
  export type OutcomeCallStruct = {
    agent: AddressLike;
    counterpart: AddressLike;
    positive: boolean;
    jobId: BigNumberish;
    reason: BytesLike;
  };

  export type OutcomeCallStructOutput = [
    agent: string,
    counterpart: string,
    positive: boolean,
    jobId: bigint,
    reason: string
  ] & {
    agent: string;
    counterpart: string;
    positive: boolean;
    jobId: bigint;
    reason: string;
  };
}

export interface MockERC8004RegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "calls"
      | "getCall"
      | "getCallCount"
      | "recordOutcome"
      | "setShouldRevert"
      | "shouldRevert"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "calls", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "getCall",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCallCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recordOutcome",
    values: [AddressLike, AddressLike, boolean, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setShouldRevert",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "shouldRevert",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "calls", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getCall", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCallCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordOutcome",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setShouldRevert",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shouldRevert",
    data: BytesLike
  ): Result;
}

export interface MockERC8004Registry extends BaseContract {
  connect(runner?: ContractRunner | null): MockERC8004Registry;
  waitForDeployment(): Promise<this>;

  interface: MockERC8004RegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  calls: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, boolean, bigint, string] & {
        agent: string;
        counterpart: string;
        positive: boolean;
        jobId: bigint;
        reason: string;
      }
    ],
    "view"
  >;

  getCall: TypedContractMethod<
    [index: BigNumberish],
    [MockERC8004Registry.OutcomeCallStructOutput],
    "view"
  >;

  getCallCount: TypedContractMethod<[], [bigint], "view">;

  recordOutcome: TypedContractMethod<
    [
      agent: AddressLike,
      counterpart: AddressLike,
      positive: boolean,
      jobId: BigNumberish,
      reason: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  setShouldRevert: TypedContractMethod<
    [_shouldRevert: boolean],
    [void],
    "nonpayable"
  >;

  shouldRevert: TypedContractMethod<[], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "calls"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, boolean, bigint, string] & {
        agent: string;
        counterpart: string;
        positive: boolean;
        jobId: bigint;
        reason: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCall"
  ): TypedContractMethod<
    [index: BigNumberish],
    [MockERC8004Registry.OutcomeCallStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCallCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "recordOutcome"
  ): TypedContractMethod<
    [
      agent: AddressLike,
      counterpart: AddressLike,
      positive: boolean,
      jobId: BigNumberish,
      reason: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setShouldRevert"
  ): TypedContractMethod<[_shouldRevert: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "shouldRevert"
  ): TypedContractMethod<[], [boolean], "view">;

  filters: {};
}
