/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IAgentJobManager {
  export type JobStruct = {
    client: AddressLike;
    provider: AddressLike;
    evaluator: AddressLike;
    token: AddressLike;
    budget: BigNumberish;
    deadline: BigNumberish;
    createdAt: BigNumberish;
    submittedAt: BigNumberish;
    status: BigNumberish;
    deliverable: BytesLike;
    reason: BytesLike;
  };

  export type JobStructOutput = [
    client: string,
    provider: string,
    evaluator: string,
    token: string,
    budget: bigint,
    deadline: bigint,
    createdAt: bigint,
    submittedAt: bigint,
    status: bigint,
    deliverable: string,
    reason: string
  ] & {
    client: string;
    provider: string;
    evaluator: string;
    token: string;
    budget: bigint;
    deadline: bigint;
    createdAt: bigint;
    submittedAt: bigint;
    status: bigint;
    deliverable: string;
    reason: string;
  };
}

export interface IAgentJobManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimExpired"
      | "claimRefund"
      | "complete"
      | "createJob"
      | "fund"
      | "getFeeRate"
      | "getJob"
      | "getPendingRefund"
      | "reject"
      | "setBudget"
      | "submit"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BudgetSet"
      | "DeadlineExtended"
      | "JobCompleted"
      | "JobCreated"
      | "JobExpired"
      | "JobFunded"
      | "JobRejected"
      | "JobSubmitted"
      | "RefundClaimed"
      | "RefundPending"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "claimExpired",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRefund",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "complete",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createJob",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fund",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFeeRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getJob",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingRefund",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reject",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setBudget",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submit",
    values: [BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimExpired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "complete", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createJob", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fund", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getFeeRate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getJob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPendingRefund",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reject", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setBudget", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "submit", data: BytesLike): Result;
}

export namespace BudgetSetEvent {
  export type InputTuple = [jobId: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [jobId: bigint, amount: bigint];
  export interface OutputObject {
    jobId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeadlineExtendedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    oldDeadline: BigNumberish,
    newDeadline: BigNumberish
  ];
  export type OutputTuple = [
    jobId: bigint,
    oldDeadline: bigint,
    newDeadline: bigint
  ];
  export interface OutputObject {
    jobId: bigint;
    oldDeadline: bigint;
    newDeadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobCompletedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    provider: AddressLike,
    payment: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    jobId: bigint,
    provider: string,
    payment: bigint,
    fee: bigint
  ];
  export interface OutputObject {
    jobId: bigint;
    provider: string;
    payment: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobCreatedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    client: AddressLike,
    provider: AddressLike,
    evaluator: AddressLike,
    token: AddressLike,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    jobId: bigint,
    client: string,
    provider: string,
    evaluator: string,
    token: string,
    deadline: bigint
  ];
  export interface OutputObject {
    jobId: bigint;
    client: string;
    provider: string;
    evaluator: string;
    token: string;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobExpiredEvent {
  export type InputTuple = [jobId: BigNumberish, refundedTo: AddressLike];
  export type OutputTuple = [jobId: bigint, refundedTo: string];
  export interface OutputObject {
    jobId: bigint;
    refundedTo: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobFundedEvent {
  export type InputTuple = [jobId: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [jobId: bigint, amount: bigint];
  export interface OutputObject {
    jobId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobRejectedEvent {
  export type InputTuple = [
    jobId: BigNumberish,
    refundedTo: AddressLike,
    reason: BytesLike
  ];
  export type OutputTuple = [jobId: bigint, refundedTo: string, reason: string];
  export interface OutputObject {
    jobId: bigint;
    refundedTo: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobSubmittedEvent {
  export type InputTuple = [jobId: BigNumberish, deliverable: BytesLike];
  export type OutputTuple = [jobId: bigint, deliverable: string];
  export interface OutputObject {
    jobId: bigint;
    deliverable: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundClaimedEvent {
  export type InputTuple = [
    client: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [client: string, token: string, amount: bigint];
  export interface OutputObject {
    client: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RefundPendingEvent {
  export type InputTuple = [
    client: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [client: string, token: string, amount: bigint];
  export interface OutputObject {
    client: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IAgentJobManager extends BaseContract {
  connect(runner?: ContractRunner | null): IAgentJobManager;
  waitForDeployment(): Promise<this>;

  interface: IAgentJobManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimExpired: TypedContractMethod<
    [jobId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimRefund: TypedContractMethod<[token: AddressLike], [void], "nonpayable">;

  complete: TypedContractMethod<
    [jobId: BigNumberish, reason: BytesLike],
    [void],
    "nonpayable"
  >;

  createJob: TypedContractMethod<
    [
      provider: AddressLike,
      evaluator: AddressLike,
      token: AddressLike,
      deadline: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  fund: TypedContractMethod<
    [jobId: BigNumberish, expectedBudget: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFeeRate: TypedContractMethod<[], [bigint], "view">;

  getJob: TypedContractMethod<
    [jobId: BigNumberish],
    [IAgentJobManager.JobStructOutput],
    "view"
  >;

  getPendingRefund: TypedContractMethod<
    [client: AddressLike, token: AddressLike],
    [bigint],
    "view"
  >;

  reject: TypedContractMethod<
    [jobId: BigNumberish, reason: BytesLike],
    [void],
    "nonpayable"
  >;

  setBudget: TypedContractMethod<
    [jobId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  submit: TypedContractMethod<
    [jobId: BigNumberish, deliverable: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimExpired"
  ): TypedContractMethod<[jobId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimRefund"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "complete"
  ): TypedContractMethod<
    [jobId: BigNumberish, reason: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createJob"
  ): TypedContractMethod<
    [
      provider: AddressLike,
      evaluator: AddressLike,
      token: AddressLike,
      deadline: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fund"
  ): TypedContractMethod<
    [jobId: BigNumberish, expectedBudget: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getFeeRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getJob"
  ): TypedContractMethod<
    [jobId: BigNumberish],
    [IAgentJobManager.JobStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPendingRefund"
  ): TypedContractMethod<
    [client: AddressLike, token: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "reject"
  ): TypedContractMethod<
    [jobId: BigNumberish, reason: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setBudget"
  ): TypedContractMethod<
    [jobId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submit"
  ): TypedContractMethod<
    [jobId: BigNumberish, deliverable: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BudgetSet"
  ): TypedContractEvent<
    BudgetSetEvent.InputTuple,
    BudgetSetEvent.OutputTuple,
    BudgetSetEvent.OutputObject
  >;
  getEvent(
    key: "DeadlineExtended"
  ): TypedContractEvent<
    DeadlineExtendedEvent.InputTuple,
    DeadlineExtendedEvent.OutputTuple,
    DeadlineExtendedEvent.OutputObject
  >;
  getEvent(
    key: "JobCompleted"
  ): TypedContractEvent<
    JobCompletedEvent.InputTuple,
    JobCompletedEvent.OutputTuple,
    JobCompletedEvent.OutputObject
  >;
  getEvent(
    key: "JobCreated"
  ): TypedContractEvent<
    JobCreatedEvent.InputTuple,
    JobCreatedEvent.OutputTuple,
    JobCreatedEvent.OutputObject
  >;
  getEvent(
    key: "JobExpired"
  ): TypedContractEvent<
    JobExpiredEvent.InputTuple,
    JobExpiredEvent.OutputTuple,
    JobExpiredEvent.OutputObject
  >;
  getEvent(
    key: "JobFunded"
  ): TypedContractEvent<
    JobFundedEvent.InputTuple,
    JobFundedEvent.OutputTuple,
    JobFundedEvent.OutputObject
  >;
  getEvent(
    key: "JobRejected"
  ): TypedContractEvent<
    JobRejectedEvent.InputTuple,
    JobRejectedEvent.OutputTuple,
    JobRejectedEvent.OutputObject
  >;
  getEvent(
    key: "JobSubmitted"
  ): TypedContractEvent<
    JobSubmittedEvent.InputTuple,
    JobSubmittedEvent.OutputTuple,
    JobSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "RefundClaimed"
  ): TypedContractEvent<
    RefundClaimedEvent.InputTuple,
    RefundClaimedEvent.OutputTuple,
    RefundClaimedEvent.OutputObject
  >;
  getEvent(
    key: "RefundPending"
  ): TypedContractEvent<
    RefundPendingEvent.InputTuple,
    RefundPendingEvent.OutputTuple,
    RefundPendingEvent.OutputObject
  >;

  filters: {
    "BudgetSet(uint256,uint128)": TypedContractEvent<
      BudgetSetEvent.InputTuple,
      BudgetSetEvent.OutputTuple,
      BudgetSetEvent.OutputObject
    >;
    BudgetSet: TypedContractEvent<
      BudgetSetEvent.InputTuple,
      BudgetSetEvent.OutputTuple,
      BudgetSetEvent.OutputObject
    >;

    "DeadlineExtended(uint256,uint64,uint64)": TypedContractEvent<
      DeadlineExtendedEvent.InputTuple,
      DeadlineExtendedEvent.OutputTuple,
      DeadlineExtendedEvent.OutputObject
    >;
    DeadlineExtended: TypedContractEvent<
      DeadlineExtendedEvent.InputTuple,
      DeadlineExtendedEvent.OutputTuple,
      DeadlineExtendedEvent.OutputObject
    >;

    "JobCompleted(uint256,address,uint256,uint256)": TypedContractEvent<
      JobCompletedEvent.InputTuple,
      JobCompletedEvent.OutputTuple,
      JobCompletedEvent.OutputObject
    >;
    JobCompleted: TypedContractEvent<
      JobCompletedEvent.InputTuple,
      JobCompletedEvent.OutputTuple,
      JobCompletedEvent.OutputObject
    >;

    "JobCreated(uint256,address,address,address,address,uint64)": TypedContractEvent<
      JobCreatedEvent.InputTuple,
      JobCreatedEvent.OutputTuple,
      JobCreatedEvent.OutputObject
    >;
    JobCreated: TypedContractEvent<
      JobCreatedEvent.InputTuple,
      JobCreatedEvent.OutputTuple,
      JobCreatedEvent.OutputObject
    >;

    "JobExpired(uint256,address)": TypedContractEvent<
      JobExpiredEvent.InputTuple,
      JobExpiredEvent.OutputTuple,
      JobExpiredEvent.OutputObject
    >;
    JobExpired: TypedContractEvent<
      JobExpiredEvent.InputTuple,
      JobExpiredEvent.OutputTuple,
      JobExpiredEvent.OutputObject
    >;

    "JobFunded(uint256,uint128)": TypedContractEvent<
      JobFundedEvent.InputTuple,
      JobFundedEvent.OutputTuple,
      JobFundedEvent.OutputObject
    >;
    JobFunded: TypedContractEvent<
      JobFundedEvent.InputTuple,
      JobFundedEvent.OutputTuple,
      JobFundedEvent.OutputObject
    >;

    "JobRejected(uint256,address,bytes32)": TypedContractEvent<
      JobRejectedEvent.InputTuple,
      JobRejectedEvent.OutputTuple,
      JobRejectedEvent.OutputObject
    >;
    JobRejected: TypedContractEvent<
      JobRejectedEvent.InputTuple,
      JobRejectedEvent.OutputTuple,
      JobRejectedEvent.OutputObject
    >;

    "JobSubmitted(uint256,bytes32)": TypedContractEvent<
      JobSubmittedEvent.InputTuple,
      JobSubmittedEvent.OutputTuple,
      JobSubmittedEvent.OutputObject
    >;
    JobSubmitted: TypedContractEvent<
      JobSubmittedEvent.InputTuple,
      JobSubmittedEvent.OutputTuple,
      JobSubmittedEvent.OutputObject
    >;

    "RefundClaimed(address,address,uint256)": TypedContractEvent<
      RefundClaimedEvent.InputTuple,
      RefundClaimedEvent.OutputTuple,
      RefundClaimedEvent.OutputObject
    >;
    RefundClaimed: TypedContractEvent<
      RefundClaimedEvent.InputTuple,
      RefundClaimedEvent.OutputTuple,
      RefundClaimedEvent.OutputObject
    >;

    "RefundPending(address,address,uint256)": TypedContractEvent<
      RefundPendingEvent.InputTuple,
      RefundPendingEvent.OutputTuple,
      RefundPendingEvent.OutputObject
    >;
    RefundPending: TypedContractEvent<
      RefundPendingEvent.InputTuple,
      RefundPendingEvent.OutputTuple,
      RefundPendingEvent.OutputObject
    >;
  };
}
