/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface EvaluatorRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "GOVERNANCE_DELAY"
      | "MAX_ACTIVE_EVALUATORS"
      | "MAX_ASSIGNMENT_RETRIES"
      | "MAX_METADATA_LENGTH"
      | "MAX_WARMUP_PERIOD"
      | "MIN_WARMUP_PERIOD"
      | "assignEvaluator"
      | "cancelProposal"
      | "executeJobManager"
      | "executeMinEvaluatorStake"
      | "getEvaluatorCount"
      | "getMetadata"
      | "getStake"
      | "isEligible"
      | "jobManager"
      | "minEvaluatorStake"
      | "owner"
      | "proposeJobManager"
      | "proposeMinEvaluatorStake"
      | "protocolToken"
      | "renounceOwnership"
      | "setMetadata"
      | "setSlashPaused"
      | "setWarmupPeriod"
      | "slash"
      | "slashPaused"
      | "stake"
      | "transferOwnership"
      | "unstake"
      | "warmupPeriod"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EvaluatorAssigned"
      | "EvaluatorMetadataUpdated"
      | "EvaluatorSlashed"
      | "JobManagerProposed"
      | "JobManagerUpdated"
      | "MinEvaluatorStakeUpdated"
      | "MinStakeExecuted"
      | "MinStakeProposed"
      | "OwnershipTransferred"
      | "ProposalCancelled"
      | "SlashPauseUpdated"
      | "Staked"
      | "Unstaked"
      | "WarmupPeriodUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "GOVERNANCE_DELAY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_ACTIVE_EVALUATORS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_ASSIGNMENT_RETRIES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_METADATA_LENGTH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_WARMUP_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_WARMUP_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "assignEvaluator",
    values: [BigNumberish, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelProposal",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeJobManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeMinEvaluatorStake",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEvaluatorCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMetadata",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStake",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isEligible",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "jobManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minEvaluatorStake",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proposeJobManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeMinEvaluatorStake",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "setMetadata", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setSlashPaused",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setWarmupPeriod",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "slash",
    values: [AddressLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "slashPaused",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "stake", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unstake",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "warmupPeriod",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "GOVERNANCE_DELAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_ACTIVE_EVALUATORS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_ASSIGNMENT_RETRIES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_METADATA_LENGTH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_WARMUP_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_WARMUP_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "assignEvaluator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeJobManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeMinEvaluatorStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEvaluatorCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isEligible", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "jobManager", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "minEvaluatorStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposeJobManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeMinEvaluatorStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSlashPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWarmupPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "slash", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "slashPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unstake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "warmupPeriod",
    data: BytesLike
  ): Result;
}

export namespace EvaluatorAssignedEvent {
  export type InputTuple = [jobId: BigNumberish, evaluator: AddressLike];
  export type OutputTuple = [jobId: bigint, evaluator: string];
  export interface OutputObject {
    jobId: bigint;
    evaluator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EvaluatorMetadataUpdatedEvent {
  export type InputTuple = [evaluator: AddressLike, metadata: string];
  export type OutputTuple = [evaluator: string, metadata: string];
  export interface OutputObject {
    evaluator: string;
    metadata: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EvaluatorSlashedEvent {
  export type InputTuple = [
    evaluator: AddressLike,
    jobId: BigNumberish,
    amount: BigNumberish,
    remainingStake: BigNumberish,
    reason: BytesLike
  ];
  export type OutputTuple = [
    evaluator: string,
    jobId: bigint,
    amount: bigint,
    remainingStake: bigint,
    reason: string
  ];
  export interface OutputObject {
    evaluator: string;
    jobId: bigint;
    amount: bigint;
    remainingStake: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobManagerProposedEvent {
  export type InputTuple = [
    newJobManager: AddressLike,
    executableAt: BigNumberish
  ];
  export type OutputTuple = [newJobManager: string, executableAt: bigint];
  export interface OutputObject {
    newJobManager: string;
    executableAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace JobManagerUpdatedEvent {
  export type InputTuple = [
    oldJobManager: AddressLike,
    newJobManager: AddressLike
  ];
  export type OutputTuple = [oldJobManager: string, newJobManager: string];
  export interface OutputObject {
    oldJobManager: string;
    newJobManager: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinEvaluatorStakeUpdatedEvent {
  export type InputTuple = [oldMinimum: BigNumberish, newMinimum: BigNumberish];
  export type OutputTuple = [oldMinimum: bigint, newMinimum: bigint];
  export interface OutputObject {
    oldMinimum: bigint;
    newMinimum: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinStakeExecutedEvent {
  export type InputTuple = [oldMinimum: BigNumberish, newMinimum: BigNumberish];
  export type OutputTuple = [oldMinimum: bigint, newMinimum: bigint];
  export interface OutputObject {
    oldMinimum: bigint;
    newMinimum: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinStakeProposedEvent {
  export type InputTuple = [
    newMinimum: BigNumberish,
    executableAt: BigNumberish
  ];
  export type OutputTuple = [newMinimum: bigint, executableAt: bigint];
  export interface OutputObject {
    newMinimum: bigint;
    executableAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalCancelledEvent {
  export type InputTuple = [key: BytesLike];
  export type OutputTuple = [key: string];
  export interface OutputObject {
    key: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SlashPauseUpdatedEvent {
  export type InputTuple = [paused: boolean];
  export type OutputTuple = [paused: boolean];
  export interface OutputObject {
    paused: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakedEvent {
  export type InputTuple = [
    evaluator: AddressLike,
    amount: BigNumberish,
    newTotal: BigNumberish
  ];
  export type OutputTuple = [
    evaluator: string,
    amount: bigint,
    newTotal: bigint
  ];
  export interface OutputObject {
    evaluator: string;
    amount: bigint;
    newTotal: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnstakedEvent {
  export type InputTuple = [
    evaluator: AddressLike,
    amount: BigNumberish,
    newTotal: BigNumberish
  ];
  export type OutputTuple = [
    evaluator: string,
    amount: bigint,
    newTotal: bigint
  ];
  export interface OutputObject {
    evaluator: string;
    amount: bigint;
    newTotal: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WarmupPeriodUpdatedEvent {
  export type InputTuple = [newPeriod: BigNumberish];
  export type OutputTuple = [newPeriod: bigint];
  export interface OutputObject {
    newPeriod: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EvaluatorRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): EvaluatorRegistry;
  waitForDeployment(): Promise<this>;

  interface: EvaluatorRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  GOVERNANCE_DELAY: TypedContractMethod<[], [bigint], "view">;

  MAX_ACTIVE_EVALUATORS: TypedContractMethod<[], [bigint], "view">;

  MAX_ASSIGNMENT_RETRIES: TypedContractMethod<[], [bigint], "view">;

  MAX_METADATA_LENGTH: TypedContractMethod<[], [bigint], "view">;

  MAX_WARMUP_PERIOD: TypedContractMethod<[], [bigint], "view">;

  MIN_WARMUP_PERIOD: TypedContractMethod<[], [bigint], "view">;

  assignEvaluator: TypedContractMethod<
    [jobId: BigNumberish, provider: AddressLike, client: AddressLike],
    [string],
    "nonpayable"
  >;

  cancelProposal: TypedContractMethod<[key: BytesLike], [void], "nonpayable">;

  executeJobManager: TypedContractMethod<
    [_jobManager: AddressLike],
    [void],
    "nonpayable"
  >;

  executeMinEvaluatorStake: TypedContractMethod<
    [newMinimum: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvaluatorCount: TypedContractMethod<[], [bigint], "view">;

  getMetadata: TypedContractMethod<[evaluator: AddressLike], [string], "view">;

  getStake: TypedContractMethod<[evaluator: AddressLike], [bigint], "view">;

  isEligible: TypedContractMethod<[evaluator: AddressLike], [boolean], "view">;

  jobManager: TypedContractMethod<[], [string], "view">;

  minEvaluatorStake: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  proposeJobManager: TypedContractMethod<
    [_jobManager: AddressLike],
    [void],
    "nonpayable"
  >;

  proposeMinEvaluatorStake: TypedContractMethod<
    [newMinimum: BigNumberish],
    [void],
    "nonpayable"
  >;

  protocolToken: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setMetadata: TypedContractMethod<[metadata: string], [void], "nonpayable">;

  setSlashPaused: TypedContractMethod<[paused: boolean], [void], "nonpayable">;

  setWarmupPeriod: TypedContractMethod<
    [newPeriod: BigNumberish],
    [void],
    "nonpayable"
  >;

  slash: TypedContractMethod<
    [
      evaluator: AddressLike,
      amount: BigNumberish,
      jobId: BigNumberish,
      reason: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  slashPaused: TypedContractMethod<[], [boolean], "view">;

  stake: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unstake: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  warmupPeriod: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "GOVERNANCE_DELAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_ACTIVE_EVALUATORS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_ASSIGNMENT_RETRIES"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_METADATA_LENGTH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_WARMUP_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_WARMUP_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "assignEvaluator"
  ): TypedContractMethod<
    [jobId: BigNumberish, provider: AddressLike, client: AddressLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelProposal"
  ): TypedContractMethod<[key: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeJobManager"
  ): TypedContractMethod<[_jobManager: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeMinEvaluatorStake"
  ): TypedContractMethod<[newMinimum: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getEvaluatorCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMetadata"
  ): TypedContractMethod<[evaluator: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getStake"
  ): TypedContractMethod<[evaluator: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isEligible"
  ): TypedContractMethod<[evaluator: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "jobManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "minEvaluatorStake"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proposeJobManager"
  ): TypedContractMethod<[_jobManager: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "proposeMinEvaluatorStake"
  ): TypedContractMethod<[newMinimum: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "protocolToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMetadata"
  ): TypedContractMethod<[metadata: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSlashPaused"
  ): TypedContractMethod<[paused: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setWarmupPeriod"
  ): TypedContractMethod<[newPeriod: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "slash"
  ): TypedContractMethod<
    [
      evaluator: AddressLike,
      amount: BigNumberish,
      jobId: BigNumberish,
      reason: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "slashPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "stake"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unstake"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "warmupPeriod"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "EvaluatorAssigned"
  ): TypedContractEvent<
    EvaluatorAssignedEvent.InputTuple,
    EvaluatorAssignedEvent.OutputTuple,
    EvaluatorAssignedEvent.OutputObject
  >;
  getEvent(
    key: "EvaluatorMetadataUpdated"
  ): TypedContractEvent<
    EvaluatorMetadataUpdatedEvent.InputTuple,
    EvaluatorMetadataUpdatedEvent.OutputTuple,
    EvaluatorMetadataUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "EvaluatorSlashed"
  ): TypedContractEvent<
    EvaluatorSlashedEvent.InputTuple,
    EvaluatorSlashedEvent.OutputTuple,
    EvaluatorSlashedEvent.OutputObject
  >;
  getEvent(
    key: "JobManagerProposed"
  ): TypedContractEvent<
    JobManagerProposedEvent.InputTuple,
    JobManagerProposedEvent.OutputTuple,
    JobManagerProposedEvent.OutputObject
  >;
  getEvent(
    key: "JobManagerUpdated"
  ): TypedContractEvent<
    JobManagerUpdatedEvent.InputTuple,
    JobManagerUpdatedEvent.OutputTuple,
    JobManagerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MinEvaluatorStakeUpdated"
  ): TypedContractEvent<
    MinEvaluatorStakeUpdatedEvent.InputTuple,
    MinEvaluatorStakeUpdatedEvent.OutputTuple,
    MinEvaluatorStakeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MinStakeExecuted"
  ): TypedContractEvent<
    MinStakeExecutedEvent.InputTuple,
    MinStakeExecutedEvent.OutputTuple,
    MinStakeExecutedEvent.OutputObject
  >;
  getEvent(
    key: "MinStakeProposed"
  ): TypedContractEvent<
    MinStakeProposedEvent.InputTuple,
    MinStakeProposedEvent.OutputTuple,
    MinStakeProposedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProposalCancelled"
  ): TypedContractEvent<
    ProposalCancelledEvent.InputTuple,
    ProposalCancelledEvent.OutputTuple,
    ProposalCancelledEvent.OutputObject
  >;
  getEvent(
    key: "SlashPauseUpdated"
  ): TypedContractEvent<
    SlashPauseUpdatedEvent.InputTuple,
    SlashPauseUpdatedEvent.OutputTuple,
    SlashPauseUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Staked"
  ): TypedContractEvent<
    StakedEvent.InputTuple,
    StakedEvent.OutputTuple,
    StakedEvent.OutputObject
  >;
  getEvent(
    key: "Unstaked"
  ): TypedContractEvent<
    UnstakedEvent.InputTuple,
    UnstakedEvent.OutputTuple,
    UnstakedEvent.OutputObject
  >;
  getEvent(
    key: "WarmupPeriodUpdated"
  ): TypedContractEvent<
    WarmupPeriodUpdatedEvent.InputTuple,
    WarmupPeriodUpdatedEvent.OutputTuple,
    WarmupPeriodUpdatedEvent.OutputObject
  >;

  filters: {
    "EvaluatorAssigned(uint256,address)": TypedContractEvent<
      EvaluatorAssignedEvent.InputTuple,
      EvaluatorAssignedEvent.OutputTuple,
      EvaluatorAssignedEvent.OutputObject
    >;
    EvaluatorAssigned: TypedContractEvent<
      EvaluatorAssignedEvent.InputTuple,
      EvaluatorAssignedEvent.OutputTuple,
      EvaluatorAssignedEvent.OutputObject
    >;

    "EvaluatorMetadataUpdated(address,string)": TypedContractEvent<
      EvaluatorMetadataUpdatedEvent.InputTuple,
      EvaluatorMetadataUpdatedEvent.OutputTuple,
      EvaluatorMetadataUpdatedEvent.OutputObject
    >;
    EvaluatorMetadataUpdated: TypedContractEvent<
      EvaluatorMetadataUpdatedEvent.InputTuple,
      EvaluatorMetadataUpdatedEvent.OutputTuple,
      EvaluatorMetadataUpdatedEvent.OutputObject
    >;

    "EvaluatorSlashed(address,uint256,uint256,uint256,bytes32)": TypedContractEvent<
      EvaluatorSlashedEvent.InputTuple,
      EvaluatorSlashedEvent.OutputTuple,
      EvaluatorSlashedEvent.OutputObject
    >;
    EvaluatorSlashed: TypedContractEvent<
      EvaluatorSlashedEvent.InputTuple,
      EvaluatorSlashedEvent.OutputTuple,
      EvaluatorSlashedEvent.OutputObject
    >;

    "JobManagerProposed(address,uint256)": TypedContractEvent<
      JobManagerProposedEvent.InputTuple,
      JobManagerProposedEvent.OutputTuple,
      JobManagerProposedEvent.OutputObject
    >;
    JobManagerProposed: TypedContractEvent<
      JobManagerProposedEvent.InputTuple,
      JobManagerProposedEvent.OutputTuple,
      JobManagerProposedEvent.OutputObject
    >;

    "JobManagerUpdated(address,address)": TypedContractEvent<
      JobManagerUpdatedEvent.InputTuple,
      JobManagerUpdatedEvent.OutputTuple,
      JobManagerUpdatedEvent.OutputObject
    >;
    JobManagerUpdated: TypedContractEvent<
      JobManagerUpdatedEvent.InputTuple,
      JobManagerUpdatedEvent.OutputTuple,
      JobManagerUpdatedEvent.OutputObject
    >;

    "MinEvaluatorStakeUpdated(uint256,uint256)": TypedContractEvent<
      MinEvaluatorStakeUpdatedEvent.InputTuple,
      MinEvaluatorStakeUpdatedEvent.OutputTuple,
      MinEvaluatorStakeUpdatedEvent.OutputObject
    >;
    MinEvaluatorStakeUpdated: TypedContractEvent<
      MinEvaluatorStakeUpdatedEvent.InputTuple,
      MinEvaluatorStakeUpdatedEvent.OutputTuple,
      MinEvaluatorStakeUpdatedEvent.OutputObject
    >;

    "MinStakeExecuted(uint256,uint256)": TypedContractEvent<
      MinStakeExecutedEvent.InputTuple,
      MinStakeExecutedEvent.OutputTuple,
      MinStakeExecutedEvent.OutputObject
    >;
    MinStakeExecuted: TypedContractEvent<
      MinStakeExecutedEvent.InputTuple,
      MinStakeExecutedEvent.OutputTuple,
      MinStakeExecutedEvent.OutputObject
    >;

    "MinStakeProposed(uint256,uint256)": TypedContractEvent<
      MinStakeProposedEvent.InputTuple,
      MinStakeProposedEvent.OutputTuple,
      MinStakeProposedEvent.OutputObject
    >;
    MinStakeProposed: TypedContractEvent<
      MinStakeProposedEvent.InputTuple,
      MinStakeProposedEvent.OutputTuple,
      MinStakeProposedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ProposalCancelled(bytes32)": TypedContractEvent<
      ProposalCancelledEvent.InputTuple,
      ProposalCancelledEvent.OutputTuple,
      ProposalCancelledEvent.OutputObject
    >;
    ProposalCancelled: TypedContractEvent<
      ProposalCancelledEvent.InputTuple,
      ProposalCancelledEvent.OutputTuple,
      ProposalCancelledEvent.OutputObject
    >;

    "SlashPauseUpdated(bool)": TypedContractEvent<
      SlashPauseUpdatedEvent.InputTuple,
      SlashPauseUpdatedEvent.OutputTuple,
      SlashPauseUpdatedEvent.OutputObject
    >;
    SlashPauseUpdated: TypedContractEvent<
      SlashPauseUpdatedEvent.InputTuple,
      SlashPauseUpdatedEvent.OutputTuple,
      SlashPauseUpdatedEvent.OutputObject
    >;

    "Staked(address,uint256,uint256)": TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;
    Staked: TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;

    "Unstaked(address,uint256,uint256)": TypedContractEvent<
      UnstakedEvent.InputTuple,
      UnstakedEvent.OutputTuple,
      UnstakedEvent.OutputObject
    >;
    Unstaked: TypedContractEvent<
      UnstakedEvent.InputTuple,
      UnstakedEvent.OutputTuple,
      UnstakedEvent.OutputObject
    >;

    "WarmupPeriodUpdated(uint64)": TypedContractEvent<
      WarmupPeriodUpdatedEvent.InputTuple,
      WarmupPeriodUpdatedEvent.OutputTuple,
      WarmupPeriodUpdatedEvent.OutputObject
    >;
    WarmupPeriodUpdated: TypedContractEvent<
      WarmupPeriodUpdatedEvent.InputTuple,
      WarmupPeriodUpdatedEvent.OutputTuple,
      WarmupPeriodUpdatedEvent.OutputObject
    >;
  };
}
