/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IReputationBridge,
  IReputationBridgeInterface,
} from "../../../../contracts/core/AgentJobManager.sol/IReputationBridge";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "jobId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "provider",
        type: "address",
      },
      {
        internalType: "address",
        name: "evaluator",
        type: "address",
      },
      {
        internalType: "bool",
        name: "completed",
        type: "bool",
      },
      {
        internalType: "bytes32",
        name: "reason",
        type: "bytes32",
      },
    ],
    name: "recordJobOutcome",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IReputationBridge__factory {
  static readonly abi = _abi;
  static createInterface(): IReputationBridgeInterface {
    return new Interface(_abi) as IReputationBridgeInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IReputationBridge {
    return new Contract(address, _abi, runner) as unknown as IReputationBridge;
  }
}
