// ---------------------------------------------------------------------------
// Shared TypeScript types for the @asp-sdk/sdk
// These mirror the server-side storage types and API response shapes,
// but are kept independent so the SDK has zero server-side dependencies.
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Domain primitives
// ---------------------------------------------------------------------------

/** All possible on-chain/off-chain states a job can be in. */
export type JobStatus =
  | 'open'
  | 'funded'
  | 'submitted'
  | 'completed'
  | 'rejected'
  | 'expired'

/** States from which no further transitions are possible. */
export type TerminalJobStatus = 'completed' | 'rejected' | 'expired'

// ---------------------------------------------------------------------------
// Storage-level records (shape returned by the API for job listings)
// ---------------------------------------------------------------------------

/**
 * Full job record as stored and returned by the API server.
 * Mirrors api/src/storage.ts JobRecord.
 */
export interface JobRecord {
  jobId: string
  agentId: string
  txHash: string
  status: JobStatus
  providerAddress: string
  /** Human-readable amount, e.g. "5.00" */
  budget: string
  deadlineMinutes: number
  createdAt: string
  updatedAt: string
}

// ---------------------------------------------------------------------------
// API response shapes
// ---------------------------------------------------------------------------

/** Response from POST /v1/agents */
export interface CreateAgentResponse {
  agentId: string
  address: string
  apiKey: string
}

/** Response from GET /v1/agents/:id/balance */
export interface BalanceResult {
  ethBalance: string
  usdcBalance: string
}

/** Response from POST /v1/jobs and POST /v1/jobs/:id/reject (synchronous) */
export interface JobResult {
  jobId: string
  txHash: string
  basescanUrl: string
  status: JobStatus
}

/**
 * Response from POST /v1/jobs/:id/fund, /submit, /complete (HTTP 202 async).
 * The transaction has been enqueued but not yet confirmed on-chain.
 * Poll GET /v1/jobs/:id (or use watchJob) to track the final status.
 */
export interface AsyncJobResult {
  jobId: string
  status: 'processing'
}

// ---------------------------------------------------------------------------
// Input parameter types
// ---------------------------------------------------------------------------

/** Parameters for AgentClient constructor */
export interface AgentClientOptions {
  /** API key obtained from POST /v1/agents. Required for authenticated routes. */
  apiKey: string
  /**
   * Base URL of the ASP API server.
   * Defaults to http://localhost:3000
   */
  baseUrl?: string
  /**
   * Per-request timeout in milliseconds.
   * If a request does not complete within this window it is aborted and a
   * BlockchainError with code REQUEST_TIMEOUT is thrown.
   * Defaults to 30 000 (30 seconds).
   */
  timeoutMs?: number
}

/** Parameters for createJob */
export interface CreateJobParams {
  /** Ethereum address of the provider agent that will execute the work. */
  providerAddress: string
  /** Human-readable budget in USDC, e.g. "5.00". */
  budget: string
  /** Job deadline in minutes. Defaults to 60 if not provided. */
  deadlineMinutes?: number
}

// ---------------------------------------------------------------------------
// Google A2A (Agent2Agent Protocol) types
//
// These types mirror the A2A specification (Linux Foundation, 2025) and are
// kept deliberately minimal — we only declare the fields the adapter uses.
// We do not import from any official A2A SDK to keep the package dependency-free.
// ---------------------------------------------------------------------------

/** A single content part within an A2A message. */
export type A2AMessagePart =
  | { type: 'text'; text: string }
  | { type: 'data'; data: unknown }

/**
 * An A2A Task — the unit of work one agent sends to another.
 * The `id` is a UUID generated by the sending agent and used to correlate
 * the task with the ERC-8183 job throughout the lifecycle.
 */
export interface A2ATask {
  /** UUID of the task, generated by the client agent. */
  id: string
  /** Optional session grouping multiple related tasks. */
  sessionId?: string
  /** The instruction payload sent to the provider agent. */
  message: {
    role: 'user'
    parts: A2AMessagePart[]
  }
  /** Arbitrary key-value pairs for domain-specific metadata. */
  metadata?: Record<string, unknown>
}

/** A single artifact produced by the provider agent as output. */
export interface A2AArtifact {
  type: 'text' | 'data' | 'file'
  /** The artifact content. Text artifacts are plain strings; data artifacts are
   *  arbitrary JSON; file artifacts are typically a URL or CID. */
  content: string | unknown
}

/**
 * The result returned by a provider agent once a task is resolved.
 * The `id` matches the originating A2ATask `id`.
 */
export interface A2ATaskResult {
  /** Same UUID as the originating A2ATask. */
  id: string
  /** Terminal status of the task. */
  status: 'completed' | 'failed' | 'working' | 'canceled'
  /** Work artifacts produced by the provider. Present when status is 'completed'. */
  artifacts?: A2AArtifact[]
  /** Arbitrary key-value pairs for domain-specific metadata (e.g. reason, jobId). */
  metadata?: Record<string, unknown>
}

/**
 * An A2A Agent Card — the capability manifest published by an agent at
 * `/.well-known/agent.json`. Clients fetch this to discover what the agent
 * can do before sending tasks.
 */
export interface A2AAgentCard {
  name: string
  description: string
  /** The root URL of the agent's A2A endpoint. */
  url: string
  version: string
  capabilities: {
    /** Whether the agent supports Server-Sent Events for streaming updates. */
    streaming?: boolean
    /** Whether the agent supports push notifications (webhooks). */
    pushNotifications?: boolean
  }
  skills: Array<{
    id: string
    name: string
    description: string
    /** MIME types or mode identifiers accepted as input (e.g. ["text/plain"]). */
    inputModes?: string[]
    /** MIME types or mode identifiers produced as output. */
    outputModes?: string[]
  }>
}

